### ISSUE TITLE
Tests Still Run Even When `checkTest` is `false`

### ISSUE THREAD

**Issue by ebebbington** [nestdotland/eggs#108] opened 2020-11-05 15:07 UTC
## 🐛 Bug Report

When i set `checkTest` inside my `egg.json` file to `false`, then run `eggs publish`, the check still runs. Alternatively, having `check` to `false` still runs all checks

Reason why set this is because the tests work locally, but not with the check flag

## To Reproduce

Use eggs v0.3.2 and set `checkTest` to false

## Expected behavior

The check for testing should not have been ran

## Actual Behavior

The check test was still being ran

## Environment

- Eggs version: 0.3.2
- Deno version: 1.5.1
- Operating system and version: MacOS v10.13.6 High Sierra

**Comment by SteelAlloy** [comment] 2020-11-05 15:15
I had several feedbacks on this behavior, some parameters are not taken into account in the configuration file.
I will investigate this problem.
In the meantime you can use the command options, they still work.
```sh
eggs publish --no-check
# or
eggs publish --no-check-tests
```

By the way, the option is named `checkTests` with an **s**, does this change anything ?

On this point, I think it's better without s but I don't want to introduce new breaking changes. I'm currently working on the new CLI, so I'm focusing on moving it forward.

**Comment by ebebbington** [comment] 2020-11-05 15:51
Cheers @oganexon, and thanks again as usual on the fast responses 👍

**Comment by SteelAlloy** [comment] 2020-12-10 21:31
@ebebbington Sorry I didn't get back to you earlier on this issue.
Does using the option `checkTests` result in the problem still being there? I can't replicate the bug.

**Comment by halvardssm** [comment] 2021-04-27 16:05
Hi @oganexon ! I can confirm this is still the case with 0.3.6, you can see the config [here](https://github.com/halvardssm/deno-nessie/blob/main/egg.json) and the CI file [here](https://github.com/halvardssm/deno-nessie/blob/main/.github/workflows/publish_nest.yml). Let me know if I can give you some more information or assist in any way 😄

**Comment by halvardssm** [comment] 2021-04-28 06:30
Some more information: when passing the `--no-check` argument through the cli, it works as intended. The problems seems to be with the parsing of the config file

**Comment by maximousblk** [comment] 2021-04-28 11:04
@halvardssm try using `checkTests` instead of `checkTest`, does that solve issue?

ref:
https://github.com/nestdotland/eggs/blob/b971caa78aa855a4d217476f8420e717ab962abb/src/context/config.ts#L35-L42

**Comment by halvardssm** [comment] 2021-04-29 12:22
Yes! That solves it, thanks!

**Closed as completed** 2021-04-29 12:23 UTC
Labels: bug report, resolved
